version: "3.9"

services:
  web:
    build: .
    container_name: django
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
      - db-ezcap
  db:
    build: ./mssql
    container_name: mssql_2017
    hostname: dohc-dw
    volumes:
      - mssql_data:/var/opt/mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Abc123++
    ports:
      - "1433:1433"
  db-ezcap:
    image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: ezcap
    hostname: ezcap
    volumes:
      - mssql_data_ezcap:/var/opt/mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Abc123++
    ports:
      - "1434:1433"
volumes:
  mssql_data:
  mssql_data_ezcap:
  static: