# Generated by Django 4.0.4 on 2022-05-12 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0001_member_init'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrderDetail',
            fields=[
                ('purchaseorderid', models.IntegerField(db_column='PurchaseOrderID', primary_key=True, serialize=False)),
                ('linenumber', models.SmallIntegerField(db_column='LineNumber')),
                ('productid', models.IntegerField(blank=True, db_column='ProductID', null=True)),
                ('unitprice', models.DecimalField(blank=True, db_column='UnitPrice', decimal_places=4, max_digits=19, null=True)),
                ('orderqty', models.SmallIntegerField(blank=True, db_column='OrderQty', null=True)),
                ('receivedqty', models.FloatField(blank=True, db_column='ReceivedQty', null=True)),
                ('rejectedqty', models.FloatField(blank=True, db_column='RejectedQty', null=True)),
                ('duedate', models.DateTimeField(blank=True, db_column='DueDate', null=True)),
                ('rowguid', models.CharField(max_length=36)),
                ('modifieddate', models.DateTimeField(db_column='ModifiedDate')),
                ('linetotal', models.DecimalField(blank=True, db_column='LineTotal', decimal_places=4, max_digits=19, null=True)),
                ('stockedqty', models.FloatField(blank=True, db_column='StockedQty', null=True)),
            ],
            options={
                'db_table': 'project1].[PurchaseOrderDetail',
                'managed': False,
            },
        ),
    ]
